VetalSiteBundle_homepageSlash:
    pattern:  /{_locale}/
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_HP:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: VetalSiteBundle_homepageSlash
        permanent: true # this is for 301
        _locale: %locale%

VetalSiteBundle_homepage:
    pattern:  /{_locale}
    defaults: { _redirect: {route: VetalSiteBundle_homepageSlash, status: 301}, _locale: %locale%  }
    requirements:
      _locale: %locales%

VetalSiteBundle_about_us:
    pattern:  /{_locale}/about_us
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_services:
    pattern:  /{_locale}/services
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_gallery:
    pattern:  /{_locale}/gallery
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_gallery_region:
    pattern:  /{_locale}/gallery/{region}
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_search:
    pattern:  /{_locale}/search
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_news:
    pattern:  /{_locale}/news
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_contacts:
    pattern:  /{_locale}/contacts
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }
    requirements:
      _locale: %locales%

VetalSiteBundle_category:
    pattern:  /{_locale}/category{category_id}
    defaults: { _controller: VetalSiteBundle:Default:show, _locale: %locale% }
    requirements:
      _locale: %locales%

currUser:
    pattern:  /{_locale}/curr_user
    defaults: { _controller: VetalSiteBundle:Default:showUserProfile, _locale: %locale% }
    requirements:
      _locale: %locales%

login:
    pattern:   /{_locale}/login
    defaults:  { _controller: VetalSiteBundle:Default:login, _locale: %locale% }
login_check:
    pattern:   /{_locale}/login_check

logout:
    pattern: /{_locale}/logout
    defaults:  {_locale: %locale% }

client:
    pattern: /{_locale}/client{profile_id}
    defaults:  { _controller: VetalSiteBundle:Default:client, _locale: %locale% }
    requirements:
      _locale: %locales%

admins:
    pattern: /{_locale}/admins
    defaults:  { _controller: VetalSiteBundle:Admin:admins, _locale: %locale% }
    requirements:
      _locale: %locales%

  