VetalSiteBundle_about_us:
    pattern:  /about_us
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_services:
    pattern:  /services
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_gallery:
    pattern:  /gallery
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_gallery_region:
    pattern:  /gallery/{region}
    defaults: { _controller: VetalSiteBundle:Default:gallery_region, _locale: %locale% }

VetalSiteBundle_search:
    pattern:  /search
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_news:
    pattern:  /news
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_contacts:
    pattern:  /contacts
    defaults: { _controller: VetalSiteBundle:Default:index, _locale: %locale% }

VetalSiteBundle_category:
    pattern:  /category/{category_id}
    defaults: { _controller: VetalSiteBundle:Default:show, _locale: %locale% }

currUser:
    pattern:  /curr_user
    defaults: { _controller: VetalSiteBundle:Default:showUserProfile, _locale: %locale% }

login:
    pattern:   /login
    defaults:  { _controller: VetalSiteBundle:Default:login, _locale: %locale% }
login_check:
    pattern:   /login_check

logout:
    pattern: /logout
    defaults:  {_locale: %locale% }

client:
    pattern: /client{profile_id}
    defaults:  { _controller: VetalSiteBundle:Default:client, _locale: %locale% }

admins:
    pattern: /admins
    defaults:  { _controller: VetalSiteBundle:Admin:admins, _locale: %locale% }

  