parameters:
  vetal_site.categories.class: Vetal\SiteBundle\Twig\VetalExtension

services:
  twig.extension.vetal_extension:
    class: %vetal_site.categories.class%
    arguments: [ @doctrine.orm.entity_manager ]
    tags:
      - { name: twig.extension }

  admin.category:
    class: Vetal\SiteBundle\Admin\CategoryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: regulatory background, label: Categories }
    arguments: [null, Vetal\SiteBundle\Entity\Category, SonataAdminBundle:CRUD]
  
  kernel.listener.exception_listener:
        class: Vetal\SiteBundle\Listener\VetalExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments: [ @service_container, @templating ]
