homepage:
    pattern:  /
    defaults: { _controller: VetalSiteBundle:Default:locale_homepage }

VetalSiteBundleFOSUserBundle:
    resource: "@VetalSiteBundle/Resources/config/routing_fos_user.yml"
    prefix:   /{_locale}

VetalSiteBundle:
    resource: "@VetalSiteBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
