VetalSiteBundleFOSUserBundle:
    resource: "@VetalSiteBundle/Resources/config/routing_fos_user.yml"
    prefix:   /

VetalSiteBundle:
    resource: "@VetalSiteBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
