security:
    encoders:
        "FOS\\UserBundle\\Model\\UserInterface": sha512
    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: 
                path:   /logout
                target: /
    access_control:
        - { path: ^/register, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN] }
        - { path: ^/category(3|4)$, roles: [ROLE_USER,ROLE_ADMIN] }

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
